### ISSUE TITLE
Option to add async scripts to the head

### ISSUE THREAD

**Issue by hph** [numical/script-ext-html-webpack-plugin#1]
Are there any plans to support moving `script` tags with `async` to the head, to enable the browser to start fetching the assets as soon as possible?

Thanks for a nice plugin!

**Comment by numical** [comment]
The location of the script tags is defined in the parent `HtmlWebpackPlugin` - see the [config](https://github.com/ampedandwired/html-webpack-plugin#configuration). My plugin _should_ simply add the `async` attribute in-situ.
Note though, that with modern browser preload scanners, I'm not sure moving to `head` will make that much difference.

**Comment by hph** [comment]
@numical Oh, wow - not sure how I missed that, thank you!

Regarding it not making much of a difference, I suppose that it's often true, but it depends on the application. By putting async script tags in the head the browser can start fetching the them sooner and without blocking rendering. There are also some cases where it might be necessary, for instance if you stream the HTTP response in chunks.
