### ISSUE TITLE
The props has not been passed

### ISSUE THREAD

**Issue by wulunyi** [numical/script-ext-html-webpack-plugin#12]
```javascript
<AsyncRoute 
path="/chat/:id"
uid={uid}
suid={suid}
info={info}
component={getChat} />																						
```

**Comment by numical** [comment]
Hiya,
Have you posted this on the correct project?
If so, you might be misunderstanding what this plugin does.
If you want to inline a script, the script cannot just be a snippet of JSX.

**Comment by wulunyi** [comment]
sorry!

**Comment by numical** [comment]
No worries :-)
Awesome avatar picture!
