### ISSUE TITLE
Ability to add random attributes to script tags

### ISSUE THREAD

**Issue by p-j** [numical/script-ext-html-webpack-plugin#14]
Hi!

I'd like to be able to add arbitrary attributes on the script tag on top of async/defer...
The main reason for that is I'm using [Cloudflare CDN's feature "Rocket Loader"](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-) and I'd like to be able to add a `data-cfasync='true'` attribute so Rocket Loader will take up the script.

Per your documentation I believe right now I can't do it. Is this something you would consider ?

**Comment by michaelpumo** [comment]
+1 For this!

It would be great to pass an object somehow that will contain any custom attributes.

I am needing to use Paper JS in my project. Paper JS runs its own superset of JS called PaperScript and I need the type attribute to be type="text/paperscript", as well as adding an ID for the canvas element that it needs to target.

e.g. `<script src="./the/path/app.js" type="text/paperscript" id="myCanvasId"></script>`

Any ideas?

**Comment by numical** [comment]
@p-j, @michaelpumo : Sorry for the long delay. I have just released v.1.8.0 with support for ['custom' attributes](https://github.com/numical/script-ext-html-webpack-plugin#configuration). 
If this is not (much!) too late, I would love to know if this is sufficient for your use cases.
