### ISSUE TITLE
Inline script is never output

### ISSUE THREAD

**Issue by alsoicode** [numical/script-ext-html-webpack-plugin#15]
I'm attempting to add an inlined script to my output that lives in the same directory as my webpack config:

```
// test.js

console.log('Hello, from WebPack');


WebPack Configuration:

plugins: [
  . . .

  new HtmlWebpackPlugin({
    cache: false,
    template: 'src/index.html',
    title: METADATA.title,
    chunksSortMode: 'dependency',
    metadata: METADATA,
    inject: 'head'
  }),

  new ScriptExtHtmlWebpackPlugin({
    inline: ['test.js']
  }),

]
```

However, I never see a console statement. What am I doing wrong?

**Comment by tiger8888** [comment]
I have the same problem

**Comment by numical** [comment]
@alsoicode, @tiger8888 - I am so sorry I have not responsed earlier - reasons...
Did you solve this problem?  I suspect it is your webpack config (specifically you loader config) rather anything specific to ScriptExt.
If you are still trying to solve this - remove the ScriptExt plugin and see if test.js is referenced in your html file without it.  If so, then it is a ScriptExt problem, if not, you need look elsewhere.

**Comment by alsoicode** [comment]
Hi @numical I just worked around the problem and hadn't revisited it.
