### ISSUE TITLE
Does this plugin support `crossorigin` attribute?

### ISSUE THREAD

**Issue by wangdahoo** [numical/script-ext-html-webpack-plugin#17]
Hey! I've tried this. not work. any suggestion?

```js
new ScriptExtHtmlWebpackPlugin({
  crossorigin: 'anonymous'
})
```

**Comment by numical** [comment]
Hi, sorry for the long delay in my response.
Check out thee support for ['custom' attributes](https://github.com/numical/script-ext-html-webpack-plugin#configuration) I have just added in v1.8.0 - it should allow you what you need.
