### ISSUE TITLE
ScriptExtHtmlWebpackPlugin: no asset with href

### ISSUE THREAD

**Issue by kukjevov** [numical/script-ext-html-webpack-plugin#27]
Hello, after upgrade to 1.8.3 version of this plugin i get this error:

>ERROR in   Error: ScriptExtHtmlWebpackPlugin: no asset with href '/dist/inline-preboot.js'
>
> - elements.js:49 replaceWithInlineElement
>    [universal-demo]/[script-ext-html-webpack-plugin]/lib/elements.js:49:21
>
>  - elements.js:39 updateScriptElement
>    [universal-demo]/[script-ext-html-webpack-plugin]/lib/elements.js:39:7
>
>  - elements.js:30 updateElement
>    [universal-demo]/[script-ext-html-webpack-plugin]/lib/elements.js:30:7
>
>  - Array.map
>
>  - elements.js:25 Object.update
>    [universal-demo]/[script-ext-html-webpack-plugin]/lib/elements.js:25:15
>
>  - plugin.js:44 Compilation.compilation.plugin
>    [universal-demo]/[script-ext-html-webpack-plugin]/lib/plugin.js:44:40
>
>  - Tapable.js:208 Compilation.applyPluginsAsyncWaterfall
>    [universal-demo]/[tapable]/lib/Tapable.js:208:13
>
>  - util.js:16 Compilation.tryCatcher
>    [universal-demo]/[bluebird]/js/release/util.js:16:23
>
>
>  - index.js:641
>    [universal-demo]/[html-webpack-plugin]/index.js:641:12
>
>  - index.js:151
>    [universal-demo]/[html-webpack-plugin]/index.js:151:16
>
>  - util.js:16 tryCatcher
>    [universal-demo]/[bluebird]/js/release/util.js:16:23
>
>  - promise.js:512 Promise._settlePromiseFromHandler
>    [universal-demo]/[bluebird]/js/release/promise.js:512:31
>
>  - promise.js:569 Promise._settlePromise
>    [universal-demo]/[bluebird]/js/release/promise.js:569:18
>
> - promise.js:614 Promise._settlePromise0
>    [universal-demo]/[bluebird]/js/release/promise.js:614:10
>
>  - promise.js:693 Promise._settlePromises
>    [universal-demo]/[bluebird]/js/release/promise.js:693:18
>
>  - async.js:133 Async._drainQueue
>    [universal-demo]/[bluebird]/js/release/async.js:133:16
>
>  - async.js:143 Async._drainQueues
>    [universal-demo]/[bluebird]/js/release/async.js:143:10
>
>  - async.js:17 Immediate.Async.drainQueues
>    [universal-demo]/[bluebird]/js/release/async.js:17:14

With previous version 1.8.2 it is working. Problem is occurs when you use this plugin in combination with virtual-module-webpack-plugin.

Here is webpack.config.js which is failing:
https://github.com/kukjevov/ng-universal-demo/blob/ad9fe9a5baa3bfe7c7628dfb15fb76b016d2bce6/webpack.config.js

**UPDATE**
It looks like that this is general problem of this version, not working even when using file, not virtual-module-webpack-plugin

**Comment by numical** [comment]
Hiya - sorry for the long delay in my response - holidays!
I think this might be due to a wrong-headed fix I added for handling public paths in v1.8.3.
Can you check with v1.8.5 (latest as of now) and see if the problem goes away?
Please let me know, ideally in less time than I took to get back to you!

**Comment by kukjevov** [comment]
Hi :).

I have tested it with your latest version and it looks fine so far. If it will go wrong again i will let you know.

Thanks
