### ISSUE TITLE
Support templates

### ISSUE THREAD

**Issue by turnerhayes** [numical/script-ext-html-webpack-plugin#29]
It seems like this plugin does nothing when a template is used in HTMLWebpackPlugin. It would be useful, if possible, for this plugin to add the attributes to the `htmlWebpackPlugin` variable that gets passed to the template somehow (in the `files` field or a separate field).

**Comment by MorganeLecurieux** [comment]
Same problem for me

**Comment by numical** [comment]
Oh really?
This is not a use case that I have tested for - I'll take a look

**Comment by hellopath** [comment]
Same issue too

**Comment by numical** [comment]
Update 6 months later - still have not had time to explore.
PR's welcome...

**Comment by hypotenuse** [comment]
https://github.com/hypotenuse/html-webpack-scripts-plugin. May be used in conjunction with templates and with inject: false. Also has simplified syntax.

**Comment by kroko** [comment]
Taking [html-webpack-template](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs) as a *spec* for template.

Setting custom one

```ejs
<!DOCTYPE html>
<html lang="en" class="noscript incapable">
<head>
  <meta charset="utf-8">
  <title><%= htmlWebpackPlugin.options.title || 'Webpack Test'%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <% for (var css in htmlWebpackPlugin.files.css) { %>
    <link href="<%= htmlWebpackPlugin.files.css[css] %>" rel="stylesheet" type="text/css">
  <% } %>
</head>
<body>
  <div class="app"></div>
  <script>
    window.__TEMPLATE_DATA__ = {};
  </script>

  <% for (var item in htmlWebpackPlugin.options.scripts) { %><%
      if (typeof item === 'string' || item instanceof String) { item = { src: item, type: 'text/javascript' } } %>
    <script<% for (var key in item) { %> <%= key %>="<%= item[key] %>"<% } %>></script>
  <% } %>

  <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
    <script async src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
  <% } %>
  
</body>
</html>
```

Using *ScriptExtHtmlWebpackPlugin* with no injection

```javascript
// ..

config.plugins.push(new HtmlWebpackPlugin({
  // ..
  inject: false,
  // ..
}));

// ----------------
// ScriptExtHtmlWebpackPlugin
config.plugins.push(new ScriptExtHtmlWebpackPlugin({
  inline: [
    /runner.*.js$/
  ]
}));

// ..
```

It only partly works.  

* `<script src="chunkN.js"></script>` for all chunks are set (template gets `htmlWebpackPlugin.files.chunks`)
* it also compiles in `<script src="runner.js"></script>`, although it was asked to be inlined...
* ... and `runner.*.js` is not inlined (nothing in `htmlWebpackPlugin.options.scripts`)

---

Thanks @hypotenuse  

```javascript
// ----------------
// HtmlWebpackScriptsPlugin
config.plugins.push(new HtmlWebpackScriptsPlugin({
  inline: /runner.*.js$/
}));
```
for the same template behaves as expected.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
