### ISSUE TITLE
html-webpack-plugin-alter-asset-tags

### ISSUE THREAD

**Issue by jantimon** [numical/script-ext-html-webpack-plugin#3]
Do you think it would make sense to refactor the plugin and use the new html-webpack-plugin-alter-asset-tags event?

**Comment by numical** [comment]
Yup - I saw your new event a while back.
Currently occupied finding a job so refactoring is low priority at the moment.
Moreover I must first get my tests working with both the latest Webpack2 beta and Webpack 1.
This plugin works fine, but  I test alongside other plugins whose config/internals have changed.

**Comment by numical** [comment]
Working on this now - but will need you to accept a PR to allow attributes with no values. It's a minor change [here](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L585) but more work to wrap with failing, then fixed test.

**Comment by numical** [comment]
[PR #514](https://github.com/ampedandwired/html-webpack-plugin/pull/514) generated.

**Comment by numical** [comment]
v1.4.0 released
