### ISSUE TITLE
Peer Dependency Webpack 3

### ISSUE THREAD

**Issue by malikshahzad228** [numical/script-ext-html-webpack-plugin#31]
Peer is outdated

**Comment by malikshahzad228** [comment]
This issue has a PR: [https://github.com/numical/script-ext-html-webpack-plugin/pull/26](https://github.com/numical/script-ext-html-webpack-plugin/pull/26)

**Comment by ai** [comment]
@numical do you need something else?

**Comment by numical** [comment]
Hiya - sorry for the delayed response - holidays.
Corrected in v.1.8.5.
