### ISSUE TITLE
Both defer and async

### ISSUE THREAD

**Issue by aseem2625** [numical/script-ext-html-webpack-plugin#32]
I tried providing same array file names to `async` and `defer` but `defer` **is not** getting added as said in `README.md` regarding `defer will be added only when it doesn't meet 1,2,3 conditions`. Is it possible to add both these attributes at the same time. It would be really useful!

**In short,**
```
	new ScriptExtHTML({
	async: ['manifest', 'vendor', 'app'], // swapping order with below defer also doesn't work
	defer: ['manifest', 'vendor', 'app']
}),
```
`defer` attribute isn't added

I don't want my files to be requested for downloading after document is loaded. Yet I want my files to execute in the same order as `manifest->vendor->app` for which `defer` and `async` together is the only choice I've

Thanks 🙂

**Comment by numical** [comment]
Hmm - I suspect that whatever is working for you is a browser-specific feature.  As best I see, according to the [w3 specs](https://www.w3.org/TR/html5/scripting-1.html#attr-script-async) the presence `async` overrides `defer` behaviour:

> There are three possible modes that can be selected using these attributes. If the async attribute is present, then the script will be executed asynchronously, as soon as it is available. If the async attribute is not present but the defer attribute is present, then the script is executed when the page has finished parsing. If neither attribute is present, then the script is fetched and executed immediately, before the user agent continues parsing the page.

So, sorry, I will not be adding this feature.

**Comment by aseem2625** [comment]
No prob. I think using defer is best approach in my case as its SSR
