### ISSUE TITLE
Inline option doesn't work

### ISSUE THREAD

**Issue by alfranchko** [numical/script-ext-html-webpack-plugin#34]
When insert the option
...
 inline: ['someChunk', 'manifest']
...
The script crashes:

TypeError: Cannot read property 'src' of undefined
  
  - common.js:10 getRawScriptName
    [frontend-dashboard]/[script-ext-html-webpack-plugin]/lib/common.js:10:47

Approve please the pullRequest https://github.com/numical/script-ext-html-webpack-plugin/pull/33/commits/00aa0e9d54759e4d401dc51742d579fc762116fa

**Comment by numical** [comment]
Sorry - forgot to report this fixed in version 1.8.8.
Thanks for the fix and huge apologies for the looong delay.
