### ISSUE TITLE
Provide option for publicPath fallback

### ISSUE THREAD

**Issue by ihym** [numical/script-ext-html-webpack-plugin#35]
When using publicPath (eg CDN), I think it would be useful if there was an option providing a fallback (maybe to local assets) in case of CDN outage. For example, a possible result would look like:
<script src="//cdn.com/chunk1.js"></script>
<script>window.xXx || document.write('<script src="/js/chunk1.js"><\/script>')</script>

**Comment by numical** [comment]
SIx months to answer!  Good grief - sorry.
And the answer is a no.
I think you're into thee realms of templating now -  much beyond thee scope of this humble plugin.
