### ISSUE TITLE
Support xhtml

### ISSUE THREAD

**Issue by shirakaba** [numical/script-ext-html-webpack-plugin#38]
# Background

## Current behaviour

We currently emit a `<script>` element with `async` and `defer` properties as follows (HTML format):

```HTML
<script async defer></script>
```

## Required behaviour

The W3 XHTML 1.0 spec gives some recommendations for writing XHTML whilst maintaining compatibility with browsers that only understand HTML:

1. [Attribute minimisation is discouraged](https://www.w3.org/TR/xhtml1/#C_3)

2. [Empty elements are discouraged](https://www.w3.org/TR/xhtml1/#C_2)

3. [Prepending a space before the trailing `/>` of empty elements is recommended](https://www.w3.org/TR/xhtml1/#C_2)

For the first part, this means that `async` and `defer` should have explicit values (["async"](https://www.w3schools.com/tags/att_script_async.asp) and ["defer"](https://www.w3schools.com/tags/att_script_defer.asp), respectively) rather than being standalone flags with implicit values.

There is some headache-inducing discussion [on StackOverflow](https://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work) about the second part, which impacts whether a self-closing element is needed. Summarily: if the web server serves the .xhtml file with `text/html` MIME type, then W3 **recommend** to add a closing tag for compatibility with browsers that *don't support XHTML*. But if targeting browsers that strictly support XHTML, provided the MIME type is `application/xhtml+xml`, then a self-closing tag will be understood (and furthermore is the recommended formatting).

```XHTML
<!-- If served with MIME: text/html -->
<script async="async" defer="defer"></script>

<!-- If served with MIME: application/xhtml+xml. Note: space before final slash recommended. -->
<script async="async" defer="defer" />
```

# Feature Proposal

So, it would be nice to have a flag for `xhtml` in the `ScriptExtHtmlWebpackPlugin` config:

```Javascript
plugins: [
  new HtmlWebpackPlugin({ xhtml: true }),
  new ScriptExtHtmlWebpackPlugin({
    async: 'bundle.js',
    defer: 'bundle.js'
    xhtml: true
  })
]
```

The default value of the `xhtml` flag would be `false`, and possible values would be `strict` (self-closing tags) or just `true` (no self-closing tags). I'm open to other possibilities here.

## Current support

Note that we can currently achieve all but the self-closing tags currently using the following configuration:

```Javascript
new ScriptExtHtmlWebpackPlugin({
    custom: [
        {
            test: /bundle.js/,
            attribute: 'async',
            value: 'async'
        },
        {
            test: /bundle.js/,
            attribute: 'defer',
            value: 'defer'
        }
    ]
}),
```

I'm not sure whether the `<script>` tags are added via appending `innerHTML` or by using `document.appendChild(document.createElement('script'))`. If the former, then we have control over whether the tags self-close. Otherwise, it's Node's own choice of what to do.

**Comment by numical** [comment]
Hi,
Thanks for the detailed explanation of what you're after - much appreciated.
There is good news and bad news.
`script-ext` does not actually create the tags - it simply decorates those created by its parent [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin).
Hence you have available the [`xhtml` configuration option](https://github.com/jantimon/html-webpack-plugin#configuration) of `html-webpack-plugin`.
That's the good news.
The bad news is that this is a simple boolean setting - not the the `true/false/strict' options you are after.
I hope it is sufficient, else you'll have to raise this request with [jantimon](https://github.com/jantimon)

**Comment by numical** [comment]
BTW - excellent profile picture!  Who is it?

**Comment by shirakaba** [comment]
> script-ext does not actually create the tags - it simply decorates those created by its parent `html-webpack-plugin`.

Ah, okay, I always get lost in webpack plugins; In any case, I've since had reason to call upon `html-webpack-plugin`'s template-editing feature, so I found that I can rely upon it to get my XHTML-valid <script>` tags:

In my `webpack.config.js`:

```Javascript
new HtmlWebpackPlugin(
{
    filename: 'ketchup.xhtml',
    template: 'src/ketchupTemplate.xhtml',
    hash: true,
    minify: false,
    xhtml: true,

    inject: false, // No longer relying on inject: true!
    links: [
        {
            href: "build/project.css"
        }
    ],
    script: [
        {
            src: "build/project.js"
        }
    ]
})
```

In the XHTML template:

```XHTML
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script async="async" type="text/javascript" src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>
<% for (var css in htmlWebpackPlugin.files.css) { %>
<link rel="stylesheet" type="text/css" href="<%= htmlWebpackPlugin.files.css[css] %>" />
<% } %>
```

> BTW - excellent profile picture! Who is it?

Thank you! It's a watercolour painting I did of [Canti](http://flcl.wikia.com/wiki/Canti) from [FLCL](https://en.wikipedia.org/wiki/FLCL) many years ago. I chose it rather arbitrarily for a GitHub picture as the only vaguely technological avatar-like image I had; though nowadays the more professional thing seems to be self photos, so soon enough he'll be gone!

Unfortunately, I experimented a bit further with a thick black waterbrush on the original, so the original painting got a bit ruined and the touched-up digital rendition is now the better of the two :P

**Comment by numical** [comment]
Glad you've solved your problem.
And thank you for introducing me to yet more esoteric anime...

**Comment by errorx666** [comment]
@numical
I'm passing `xhtml: true` to `HtmlWebpackPlugin`.  I see the `link` tags end with `/>` as desired, but the `async` attribute is still rendering as `async` (invalid XML, and thus, XHTML) instead of the XHTML-compliant `async="async"` form.

It looks like the solution @shirakaba found is a workaround to the problem, not an actual resolution to the bug that the `xhtml` flag is not honored.
