### ISSUE TITLE
ability to move inlined scripts to the head tag

### ISSUE THREAD

**Issue by mayank23** [numical/script-ext-html-webpack-plugin#39]
Hi 😄 

I want to move scripts which are inlined, to the top of the HEAD tag. I patched the plugin to do this, however, would it be fine if I made a Pull Request for this feature? This basically allows us to leverage the default html-webpack-plugin template and still reorder the scripts.

Possible implementation:
```
// elements.js replaceWithInlineElement method
...  
if(options.inlineAtHead){
  newtag.__mark_inlined__ = true;
}
...
```
```
// plugin.js compilation.plugin handler

if(options.inlineAtHead){
  // elements.update marks inlined script tags
  const moveToHead = pluginArgs.body.filter((tag) => {
    return tag.tagName === 'script' && tag.__mark_inlined__;
  });
  pluginArgs.body = pluginArgs.body.filter((tag) => {
    return !(tag.tagName === 'script' && tag.__mark_inlined__);
  });
  moveToHead.forEach((tag) => {
    delete tag.__mark_inlined__;
  });
 // can inline at top of head or bottom of head. (e.g, need to do something immediately or not) 
  if(options.inlineAtHead === 'top'){
    pluginArgs.head = [...moveToHead, ...pluginArgs.head];
  }else{
    pluginArgs.head = [...pluginArgs.head, ...moveToHead];
  }
```

actual usage in webpack config

```
[
...
    new ScriptExtHtmlWebpackPlugin({
      inline: ['detect-browser'],
      inlineAtHead: 'top'
    }),
...
]
```

Thank you!

**Comment by numical** [comment]
Hi, sorry for the long delay in answering this.
This has been asked for before but is not (elegantly) possible without a change to html-webpack-plugin.
See:
* https://github.com/numical/script-ext-html-webpack-plugin/issues/6
* https://github.com/numical/style-ext-html-webpack-plugin/issues/15

Your solution is certainly more elegant than what I do in the sister plugin [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin#use-case-specifying-position-of-style-element) where I use regex's to change the outputted HTML.  

However it still involves adding properties to objects that I do not control.  I worry it would brittle to the changes in the underlying webpack and html-webpack-plugin, and might not play well with other plugins.

I'm happy to take a look at a spike PR (i.e. don't worry about full testing unless you are a TDD purist) but I'm not yet convinced.

Thanks for the offer!

**Comment by numical** [comment]
Closed as no PR forthcoming :-(

**Comment by xitter** [comment]
I was able to do with help of [html-webpack-injector](https://github.com/thearchitgarg/html-webpack-injector):

```
entry: {
   app: './app.js',
   appInline_head: './appInline.js',        // Inline script
},
plugins: [
  new HtmlWebpackPlugin({
    inject: 'body',
    template: './app/index.ejs',
    chunks: ['app', 'appInline_head'],
    filename: 'index.html'
  });
  new HtmlWebpackInjector(),
  new ScriptExtHtmlWebpackPlugin({
    inline: ['appInline_head'],
   }),
]
```
This would insert inline script in head tag while the app script in the body tag.
