### ISSUE TITLE
Script neither src nor inline

### ISSUE THREAD

**Issue by Croissong** [numical/script-ext-html-webpack-plugin#4]
In my use case i want to render a script tag inside {{#if /if}} as is:
```
{{#if htmlWebpackPlugin.options.metadata.isDevServer}}
  <script>window.initial_state = {{{ htmlWebpackPlugin.options.INITIAL_STATE }}}</script>
  {{else}}
  <script>window.initial_state = <%= {:safe, initial_state} %></script>
  {{/if}}
```

This throws the error ` Cannot read property '1' of null`.
As far as i can tell, replaceScriptElements() expects each script tag to either have a src tag or be in the inline options.
I fixed it like this but you probably want to do it more elegantly:
```
var scriptName = SRC_PATTERN.exec(scriptElement);
    if(scriptName) {
      scriptName = scriptName[1]; 
      if (matches(scriptName, options[INLINE])) {
        return generateInlineScriptElement(scriptName, compilation);
      } else {
        return generateSrcScriptElement(options, scriptName);
      }
    } else {
      return scriptElement;
```

Thank you for your work on the project!

**Comment by numical** [comment]
Hi, thanks for the issue.
I am working right now on a [major rewrite](https://github.com/numical/script-ext-html-webpack-plugin/issues/3) that should negate any issues with templates.
Could I have your template and HtmlWebpackPlugin config so that I can write a failing test to check this?

**Comment by Croissong** [comment]
[template](https://github.com/Croissong/blog-app/blob/236f869bf5fe5dfa9d40d2d43a2538e98b812a57/src/index.hbs#L58)
[plugin](https://github.com/Croissong/blog-app/blob/236f869bf5fe5dfa9d40d2d43a2538e98b812a57/config/webpack.common.js#L236)
Does this work or do you need a minimal example?

**Comment by numical** [comment]
That should be sufficient, thanks!

**Comment by numical** [comment]
Hi - progress update - the new implementation works fine with template scripts - see [the test](https://github.com/numical/script-ext-html-webpack-plugin/blob/switch-to-alter-assets-event/spec/core-spec.js#L338) here.
So ready for release, if/when [this PR](https://github.com/ampedandwired/html-webpack-plugin/pull/514) for [HtmlWebpackPlugin](https://github.com/ampedandwired/html-webpack-plugin)  is accepted by @jantimon.

I will leave this issue open until then.  
If the PR is not accepted the I will have to think again!

**Comment by numical** [comment]
v1.4.0 released - hopefully fixes your issue
