### ISSUE TITLE
webpack 4 not work

### ISSUE THREAD

**Issue by aymonYU** [numical/script-ext-html-webpack-plugin#41]
when my webpack update to version 4.0.1，it report 'TypeError: callback is not a function'

**Comment by sherlock1982** [comment]
More detailed trace:

```
ERROR in   TypeError: callback is not a function

  - plugin.js:66 compilation.plugin
    [Webclient]/[script-ext-html-webpack-plugin]/lib/plugin.js:66:11


  - new Promise


  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [Webclient]/[html-webpack-plugin]/[tapable]/lib/Hook.js:35:21

  - index.js:645
    [Webclient]/[html-webpack-plugin]/index.js:645:47

  - index.js:182 Promise.resolve.then.then.then.then.then.then.then.result
    [Webclient]/[html-webpack-plugin]/index.js:182:18
```

Looks like one needs to use promise variant now.

**Comment by ai** [comment]
@numical maybe you need fixes like this? https://github.com/webpack-contrib/uglifyjs-webpack-plugin/commit/23b1b38003953c2952879b5613ef7bafa9678c3c

**Comment by sherlock1982** [comment]
The fix is rather obvious here. Simply don't call callback because plugin is synchronous.

**Comment by ai** [comment]
@sherlock1982 can you make a PR?

**Comment by sherlock1982** [comment]
I'm in the process. Though fix is rather simple I also want to fix tests for Webpack4

**Comment by oychao** [comment]
same question here, @sherlock1982 nice work.

**Comment by numical** [comment]
Webpack 4 supported in v2.0.0 of this plugin thanks to [this PR](https://github.com/numical/script-ext-html-webpack-plugin/pull/42)
