### ISSUE TITLE
Multiple html plugins

### ISSUE THREAD

**Issue by furstenheim** [numical/script-ext-html-webpack-plugin#43]
Hi,
I have the following use case. In a webpack config I'm creating several html files as in [this question](https://stackoverflow.com/questions/39798095/multiple-html-files-using-webpack). I can't find any way in the documentation to treat that case with script ext html webpack plugin. That is:

    plugins: [
      new HtmlWebpackPlugin({
        filename: 'index.html',
        template: 'src/index.html',
        chunks: ['main']
      }),
      new HtmlWebpackPlugin({
        filename: 'example.html',
        template: 'src/example.html',
        chunks: ['exampleEntry']
      }),
      // I want this to affect only index.html
      new ScriptExtHtmlWebpackPlugin()     
    ]

Is it possible to do it with this plugin? In the README there are only examples on how to filter the chunks, but not the destination.

Thanks

**Comment by numical** [comment]
Hi,
It would be possible to modify the plugin to use the same mechanism I used for the sister plugin [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin) - see the documentation [here](https://github.com/numical/style-ext-html-webpack-plugin#use-case-multiple-html-files).
However there would be a fair bit of code and additional testing to write.  It can go into my backlog but unlikely to be done soon.  Happy to accept a PR ... :-)

**Comment by roypeled** [comment]
I'm having the same problem.
When there are multiple HtmlWebpackPlugin, ScriptExtHtmlWebpackPlugin completely fails to work.

**Comment by omeryagmurlu** [comment]
I'm also having the same problem.
Especially with Electron apps, where multiple html files for multiple renderers is a nice necessity

**Comment by creage** [comment]
Any progress on that issue?

**Comment by XiaoWinter** [comment]
I've seen a lot of similar issues  in this project，Is there any way to deal with this problem？

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
