### ISSUE TITLE
Support custom value callback

### ISSUE THREAD

**Issue by devpreview** [numical/script-ext-html-webpack-plugin#44]
For example:

```javascript
new ScriptExtHtmlWebpackPlugin({
  custom: [
    {
      test: /\.js$/,
      attribute: 'onload',
      value: (entry) => {return 'alert("loaded ' + entry + '");'}
     }
   ]
}),
```

**Comment by numical** [comment]
Can you explain the use case?
When is the function called and what is passed to it?

**Comment by lili21** [comment]
I think it would be useful for things like tracking the resources which load failed.

```js
new ScriptExtHtmlWebpackPlugin({
  custom: [
    {
      test: /\.js$/,
      attribute: 'onerror',
      value: e => { // track the resource }
     }
   ]
}),
```

**Comment by numical** [comment]
Sorry - still not clear on when the function wuld be called and hat data would be passed.
Happy to re-open if more clarity available - or better a spike-PR! :-)

**Comment by ykxkknd2** [comment]
@numical I need this too.  For example, the resource requested fails, and the error event is reported to the log.The callback parameter is the filename. Like this
```
new ScriptExtHtmlWebpackPlugin({
  custom: [
    {
      test: /\.js$/,
      attribute: 'onerror',
      value: filename => report(filename)
     }
   ]
}),
```
