### ISSUE TITLE
Is it possible to use custom attributes with preloaded scripts?

### ISSUE THREAD

**Issue by DenRedsky** [numical/script-ext-html-webpack-plugin#49]
Hello, is it possible to use custom attributes with preloaded scripts?

**Comment by numical** [comment]
Not yet.
Looking at this with [PR 53](https://github.com/numical/script-ext-html-webpack-plugin/pull/53)

**Comment by numical** [comment]
This is available from [v2.1.0](https://github.com/numical/script-ext-html-webpack-plugin/tree/v2.1.0) onwards.
Let me know if it does not work for you.
