### ISSUE TITLE
ScriptExtHtmlWebpackPlugin: no asset with href

### ISSUE THREAD

**Issue by avivaWang** [numical/script-ext-html-webpack-plugin#50]
below is my webpack config.
`/**
 * @file
 * @author by baidu on 2018/9/12.
 */
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');

module.exports = {
    entry: {
        index: './src/entry/index.js',
        startup: './src/entry/test.js'
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.sass$/,
                use: ['style-loader', 'css-loader', 'sass-loader']
            },
            {
                test: /\.js$/,
                use: 'babel-loader',
                exclude: /node_modules/
            },
            {
                test: /\.san$/,
                use: 'san-loader'
            },
            {
                test: /\.svg|.jpg|.jpeg|.png$/,
                use: 'file-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'san demo',
            template: './src/views/layout.tpl',
            filename: './views/layout.tpl',
            cache: false
        }),
        new ScriptExtHtmlWebpackPlugin({
            inline: ['startup'],
            preload: /\.js$/,
            defaultAttribute: 'async'
        })
    ]
};`

then I got this:

**Comment by avivaWang** [comment]
`const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');

module.exports = {
    entry: {
        index: './src/entry/index.js',
        startup: './src/entry/test.js'
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.sass$/,
                use: ['style-loader', 'css-loader', 'sass-loader']
            },
            {
                test: /\.js$/,
                use: 'babel-loader',
                exclude: /node_modules/
            },
            {
                test: /\.san$/,
                use: 'san-loader'
            },
            {
                test: /\.svg|.jpg|.jpeg|.png$/,
                use: 'file-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'san demo',
            template: './src/views/layout.tpl',
            filename: './views/layout.tpl',
            cache: false
        }),
        new ScriptExtHtmlWebpackPlugin({
            inline: ['startup'],
            preload: /\.js$/,
            defaultAttribute: 'async'
        })
    ]
};`

then I got this:
![image](https://user-images.githubusercontent.com/8251871/45409105-db981580-b6a0-11e8-9f1e-8a24c3f16733.png)

the version:
ScriptExtHtmlWebpackPlugin: 2.0.1
webpack: 4.1.1

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
