### ISSUE TITLE
Preloads are incompatible with webpack-subresource-integrity

### ISSUE THREAD

**Issue by dantman** [numical/script-ext-html-webpack-plugin#55]
The preloads in this plugin are incompatible with [`webpack-subresource-integrity`](https://www.npmjs.com/package/webpack-subresource-integrity) (SriPlugin).

The SriPlugin adds `integrity` attributes to chunks and expects you to set WebPack's output.crossOriginLoading to anonymous.

However none of the attributes added to the script are used when creating the preload. As a result Chrome fetches the script twice.

Even if you use a custom attribute to force this plugin to set the crossorigin is should automatically know about, it still loads twice because the integrity also needs to be copied to the preload. Which can't be done manually because the integrity is a generated hash and can't be known ahead of time.

**Comment by amits-dev** [comment]
Is there any update/workaround for this?

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
