### ISSUE TITLE
Option to not delete inlined assets

### ISSUE THREAD

**Issue by Alxandr** [numical/script-ext-html-webpack-plugin#56]
I would like for the inlined assets not to be deleted. Could it be added as an option?

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
