### ISSUE TITLE
[Feature] Support .mjs file extension

### ISSUE THREAD

**Issue by l-easwar-akiyama** [numical/script-ext-html-webpack-plugin#58]
## Request for `.mjs` file support. 

For the following config, script is not injected into the html

### Input: 
```
plugins: [
  new HtmlWebpackPlugin({}),
  new ScriptExtHtmlWebpackPlugin({  module: ['bundle'] }),
],
output: {
  path: `${__dirname}/build`,
  filename: 'bundle.mjs',
}
```
### Current Output:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Webpack App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
  </head>
  <body></body>
</html>
```
### Required Output:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Webpack App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
  </head>
  <body>
    <script src="/bundle.js" type="module"></script>
  </body>
</html>
```

The same config works perfectly fine, if the bundled filename has `.js` extension.

**Comment by parties** [comment]
Try:
```
module: /.*bundle.*\.mjs$/
```

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
