### ISSUE TITLE
Preloading Fonts

### ISSUE THREAD

**Issue by jhoover4** [numical/script-ext-html-webpack-plugin#65]
Maybe this isn't the right place for this, but I'm just trying to preload my font files, but can't seem to find a way to do it. Is there a way with this plugin to inject the path into the head so they can be preloaded?

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
