### ISSUE TITLE
Proposal: Allow setting custom attributes on stylesheet/CSS link tags

### ISSUE THREAD

**Issue by alex-ketch** [numical/script-ext-html-webpack-plugin#72]
Hi there, and thanks for this plugin, it's come in very handy for setting custom attributes on injected chunks.

A use case I've come across is needing to set attributes on stylesheet links, however due [to this line of code](https://github.com/numical/script-ext-html-webpack-plugin/blob/095dc8c210c428d04d3acf0a6f2bd8cc7ad2dba2/lib/common.js#L8) checking whether the link tag has a `as="script"` attribute, stylesheet  link tags (`<link rel="stylesheet" …`)  are skipped.

Right now I've solved our problem in a fork with a [rudimentary change](https://github.com/stencila/script-ext-html-webpack-plugin/commit/5f07d97ed16d4462bede67d83048b7660c110a9f), but I was wondering if this was something that was in scope for this plugin, and if a PR for this functionality would be wanted.

Also, if there's a better plugin for achieving this please let me know.

**Comment by onurozkan** [comment]
@numical 

"test" attribute gives us a power to select whatever file we want, so basically current implementation supports mimetypes other than script. Only thing we need to do, dynamically fill "as" attribute.

Here is very basic implementation, not perfect, but could help lots of people with very little effort.

https://github.com/onurozkan/script-ext-html-webpack-plugin/commit/0265a5cae3ac6502e4cd27ecbfd004a384f70afa

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
