### ISSUE TITLE
Can we add custom attributes to inlined scripts?

### ISSUE THREAD

**Issue by jkeys089** [numical/script-ext-html-webpack-plugin#74]
Is it possible to match a script with no `src` (i.e. a script that was already inlined)? The use case would be to add a `nonce` attribute to an inlined script.

**Comment by crhistianramirez** [comment]
I'm also looking to try and solve this. After a bit of testing I noticed that only scripts that are added dynamically are evaluated, ie scripts produced as part of the webpack bundling process. I'm assuming that your inline script, like mine, is part of a template so it isn't a script that is evaluated.

It may be considered out of scope but I think it'd be very useful for this library to handle not only scripts that are generated during the bundling process but also scripts that are a part of a template.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
