### ISSUE TITLE
while the inline file preload link has not be deleted?

### ISSUE THREAD

**Issue by qiangf811** [numical/script-ext-html-webpack-plugin#77]
i used for webpack runtimeChunk。
```js
new ScriptExtHtmlWebpackPlugin({
      inline: /runtime~.+\.js$/
})
```
of course the code has be injected in index.html,but the preload link  has existed
```html
 <link href=js/chunk-vendors.1e5c55d3.js rel=preload as=script>
 <link href=js/runtime~app.2f2e1145.js rel=preload as=script>
 <link href=css/app.b087a504.css rel=stylesheet>
```
why? so that it will cause a error in chrome.

what should i do.

**Comment by Lynn-cc** [comment]
我也有一样的问题，请问你怎么解决的？
I have the same problem, could you tell me how you solve it ?

**Comment by qiangf811** [comment]
> 我也有一样的问题，请问你怎么解决的？ I have the same problem, could you tell me how you solve it ?
给preload插件配置fileBlacklist，将runtime文件过滤掉

**Comment by Lynn-cc** [comment]
> > 我也有一样的问题，请问你怎么解决的？ I have the same problem, could you tell me how you solve it ?
> > 给preload插件配置fileBlacklist，将runtime文件过滤掉

谢谢回复。
我最后是换了个插件`html-webpack-inline-source-plugin` 来解决的。
