### ISSUE TITLE
For #53, options should be added to achieve control

### ISSUE THREAD

**Issue by Hill-98** [numical/script-ext-html-webpack-plugin#79]
In some cases, I only want to add custom attributes to the script tag, and not include preload or prefetch link tags, such as `onerror` or other attributes, so I think we should add options to realize whether to add custom attributes to the link tag.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
