### ISSUE TITLE
Filenames requiring URL escaping are not handled correctly

### ISSUE THREAD

**Issue by Geo1088** [numical/script-ext-html-webpack-plugin#82]
If html-webpack-plugin spits out a script tag with URL escape sequences (e.g. `%20`) in its `src`, script-ext-webpack-plugin will fail to find the correct bundle file:

```
ERROR in ScriptExtHtmlWebpackPlugin: no asset with href 'Debug%20info.js'
```

In my case, I was generating JS files with spaces in the name, and then trying to inline them. I solved my issue by changing

```js
output: {
  filename: '[name].js',
},
```
to use `[hash]` instead of `[name]`.

**Comment by numical** [comment]
Hello - I'm sorry to say that this plugin is no longer being maintained.  I have tried to close all issues ahead of doing this but instead have found that the issue list just keeps growing.  I simply do not have the time to keep up.  Sorry.
Please keep an eye on the [README](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) where I will record anyone who forks this repo with the intention to supporting it in the future.
