### ISSUE TITLE
[webpack 5] `publicPath: "auto"` handling

### ISSUE THREAD

**Issue by sokra** [numical/script-ext-html-webpack-plugin#83]
see https://github.com/jantimon/html-webpack-plugin/issues/1514

script-ext-html-webpack-plugin has the same problem, as it calculates the publicPath again

cc @jantimon

**Comment by numical** [comment]
@sokra - thanks for this.  Sods law that my first interaction with the brains behind webpack is to tell him that I will no longer be supporting this plugin and hence will not be upgrading support for Webpack 5.  :-(
